### ISSUE TITLE
http://localhost/ is unreachable

### ISSUE THREAD

**Issue by raihanflores** [ninech/netbox-docker#3]
HI,

Everything was installed without issues and I can also see that all 3 containers are running. But accessing http://localhost doesn't seem to work. I get `This site can’t be reached` is there something that I missed? 

command: `docker-compose up -d`

Thanks,
Ryann

**Comment by born4new** [comment]
Hey @raihanflores,

You are actually missing the host port here...

If you do a `docker-compose ps`, you'll see to which port is your `nginx` install mapped to. In my case, the port is `32768`:

```shell
         Name                        Command               State               Ports              
-------------------------------------------------------------------------------------------------
netboxdocker_netbox_1     /docker-entrypoint.sh            Up                                     
netboxdocker_nginx_1      nginx -g daemon off; -c /e ...   Up      443/tcp, 0.0.0.0:32768->80/tcp 
netboxdocker_postgres_1   docker-entrypoint.sh postgres    Up      5432/tcp  
```

Hitting http://localhost:32768 should work for you :).

@cimnine Don't we want to link to the host port 80 by default [here](https://github.com/ninech/netbox-docker/blob/master/docker-compose.yml#L21)? Either that or changing the README, so that we can have a seamless experience :).

**Comment by cimnine** [comment]
Port 80 is unfeasible, because it is a privileged port and requires superuser permissions for a program to bind to.

Updating the README would be the way to go IMO.

**Comment by cimnine** [comment]
Thank you for reporting this. I hope the README is clearer now.
